// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgCN_9WYZ-q88vjZADhb-gpx2O3yKLywI',
    appId: '1:646281323733:web:b7b541bcc1eb03cceaee5c',
    messagingSenderId: '646281323733',
    projectId: 'spotify-clone-4444',
    authDomain: 'spotify-clone-4444.firebaseapp.com',
    storageBucket: 'spotify-clone-4444.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkCPdDnCDDlfX7PScxAg-0RPcWgcBV4xA',
    appId: '1:646281323733:android:0a21f76079d689fdeaee5c',
    messagingSenderId: '646281323733',
    projectId: 'spotify-clone-4444',
    storageBucket: 'spotify-clone-4444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmXcDe3h_WYHl56EeEmJrVJRvm_bbEq2Q',
    appId: '1:646281323733:ios:5cbc0afce03304ddeaee5c',
    messagingSenderId: '646281323733',
    projectId: 'spotify-clone-4444',
    storageBucket: 'spotify-clone-4444.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmXcDe3h_WYHl56EeEmJrVJRvm_bbEq2Q',
    appId: '1:646281323733:ios:5cbc0afce03304ddeaee5c',
    messagingSenderId: '646281323733',
    projectId: 'spotify-clone-4444',
    storageBucket: 'spotify-clone-4444.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgCN_9WYZ-q88vjZADhb-gpx2O3yKLywI',
    appId: '1:646281323733:web:ecf3d5674be7023beaee5c',
    messagingSenderId: '646281323733',
    projectId: 'spotify-clone-4444',
    authDomain: 'spotify-clone-4444.firebaseapp.com',
    storageBucket: 'spotify-clone-4444.firebasestorage.app',
  );
}
